import json

SECTIONS = {
    'Modern Argentine Tango': 'Tango Argentino Moderno',
    'Contemporary Social Tango': 'Tango Social Contemporáneo',
    'Early Buenos Aires Tango (c. 1916)': 'Tango Temprano de Buenos Aires (c. 1916)',
    'Early Tango Around the World (1911-1915)': 'Tango Temprano en el Mundo (1911-1915)',
    'Post-War Tango': 'Tango de Posguerra',
}

SUBS = {
    'Walking': 'Caminatas',
    'Rocking': 'Hamacadas',
    'Ochos': 'Ochos',
    'Barridas': 'Barridas',
    'Castigadas & Ganchos': 'Castigadas y Ganchos',
    'Molinetes': 'Molinetes',
    'Giros': 'Giros',
    'Eight Count Basic': 'Base de Ocho Tiempos',
    'Argentine Tango Mixer': 'Mixer de Tango Argentino',
    'Fans': 'Abanicos (Fans)',
    'Promenades': 'Promenades (Paseos)',
    'Grapevines': 'Viboritas (Grapevines)',
    'Ruedas': 'Ruedas',
    'Media Lunas (Puzzle Steps)': 'Media Lunas (Pasos Rompecabezas)',
    'Rocking Steps': 'Pasos Hamacados',
    'Pivots': 'Pivotes',
    'Added Styling': 'Adornos',
    'Dips & Lunges': 'Caídas y Estocadas',
    'Alternate Timings': 'Ritmos Alternativos',
    'Advanced Concepts': 'Conceptos Avanzados',
    'Sequences': 'Secuencias',
    'Full Song Demo': 'Demo de una Canción Completa',
    'Pasos Paseos': 'Pasos Paseos',
    'Saltitos': 'Saltitos',
    'Cruces de Píes': 'Cruces de Pies',
    'Vueltas': 'Vueltas',
    'Paso Lateral': 'Paso Lateral',
    'Paso Pique Acompasado': 'Paso Pique Acompasado',
    'El Ocho': 'El Ocho',
    'Sentadas': 'Sentadas',
    'Media Lunas': 'Media Lunas',
    'Cortes': 'Cortes',
    'Scissors': 'Tijeras',
    'Three Step Promenade': 'Promenade de Tres Pasos',
    'La Rueda': 'La Rueda',
    'Tango Waltzes': 'Valses de Tango',
    'Grapevines & Other Crosses': 'Viboritas y Otros Cruces',
    'Chassés': 'Chassés',
    'Floorplay': 'Juegos de Pies en el Piso',
    'Lunges and Dips': 'Estocadas y Caídas',
    'Changing the Feet': 'Cambios de Pie',
    'Fantasies on the Tango': 'Fantasías sobre el Tango',
    '1920s English Tango Sequences': 'Secuencias de Tango Inglés (años 1920)',
    '1920s American Tango': 'Tango Americano (años 1920)',
    '1930s American Tango': 'Tango Americano (años 1930)',
}

T = {
    # --- Tango Argentino Moderno ---
    'awa': 'Caminata',
    'aso': 'Paso Afuera',
    'acr': 'La Cruzada',
    'ase': 'Sentada (Ida y Vuelta)',
    'asw': 'Caminata Sincopada',
    'abo': 'Ochos Atrás',
    'aff': 'Ochos al Costado (desde la Cruzada)',
    'afb': 'Ochos Atrás al Costado',
    'agb': 'Gancho en Ochos Atrás al Costado',
    'aml': 'Molinete Largo',
    'agg': 'Giro en Viborita (Grapevine)',
    'aeb': 'Base de Ocho Tiempos',
    'aeh': 'Hamaca en la Base de Ocho Tiempos',
    'aeo': 'Ochos en la Base de Ocho Tiempos',
    'aec': 'Castigada en la Base de Ocho Tiempos',
    'aeg': 'Gancho en la Base de Ocho Tiempos',
    'asx': 'Base de Seis Tiempos',
    'asv': 'Base de Siete Tiempos',
    'atm': 'Mixer de Tango Argentino (Cambio de Pareja)',
    # --- Tango Social Contemporáneo ---
    'spl': 'Abanico con Giro a la Izquierda en Promenade (Base del Tango Social)',
    'spr': 'Abanico con Giro a la Derecha en Promenade',
    'sts': 'Paso del Problema (Trouble Step)',
    'srl': 'Abanico Hamacado con Giro a la Izquierda',
    'srr': 'Abanico Hamacado con Giro a la Derecha',
    'slg': 'Abanico en Viborita del Líder',
    'sfg': 'Abanico en Viborita del Seguidor',
    'sef': 'Abanico de Ocho Tiempos (Lateral, Adelante, Atrás)',
    'sbf': 'Abanico Retrocediendo (Base del Tango Americano)',
    'sbl': 'Abanico Retrocediendo con Giro a la Izquierda',
    'sfh': 'Promenade de Cinco Pasos (Cambio de Manos)',
    'sfs': 'Promenade de Cinco Pasos (Posición Escorpión)',
    'sch': 'Chassé de Tango',
    'ssc': 'Pasos Laterales en Escorpión',
    'ssl': 'Pasos Laterales en Escorpión (Versión Larga)',
    'sml': 'Media Luna en Promenade',
    'srm': 'Media Luna en Promenade Repetida',
    'smf': 'Media Luna en Promenade y Promenade de Cinco Pasos',
    'sgd': 'Viborita con Salida en Picada',
    'sgl': 'Viborita Larga',
    'sgc': 'Viborita (Ritmo de Chassé)',
    'sgo': 'Viborita (Más Rápida que la Música)',
    'sgf': 'Viborita (Solo el Seguidor)',
    'sdg': 'Viborita del Ebrio',
    'spo': 'Giro Pomander',
    'sgr': 'Rueda en Viborita',
    'sso': 'Ocho Simple',
    'smo': 'Ochos Múltiples',
    'scc': 'Contracruce',
    'sfo': 'Solo del Seguidor',
    'sft': 'Adorno de Toques',
    'sfk': 'Adorno de Patadas',
    'sfw': 'Adorno de Barridas',
    'sfe': 'Adorno Punto Pluma (Feather Stitch)',
    'ssw': 'Adorno de Pivoteos Rápidos',
    'sla': 'Postura en "A" del Líder',
    'sro': 'De Promenade a Ochos',
    'sth': 'Promenade de Tres Pasos',
    'sbo': 'Media Luna Sanjuanina (Paso de Caja)',
    'spu': 'Media Luna Puntana (Caja Hamacada)',
    'slo': 'Media Luna Lola (Caja Trapezoidal)',
    'smn': 'Molinete Hamacado',
    'str': 'Molinete Hamacado Corto',
    'smc': 'Molinete (Ritmo de Chassé)',
    'sbr': 'Corte Hamacado Retrocediendo',
    'src': 'Corte Hamacado Simple',
    'sdr': 'Corte Hamacado Doble',
    'srw': 'Estocada Rockaway',
    'srf': 'Estocada Rockaway (Versión Solo del Seguidor)',
    'srp': 'Promenade Hamacada (Ritmo de Chassé)',
    'spv': 'Pivotes (Ritmo de Chassé)',
    'svu': 'Pivotes y Giro Bajo el Brazo',
    'ssp': 'Lustrada de Zapato del Líder',
    'shr': 'Golpe de Taco del Líder',
    'sat': 'Usar Todo el Tiempo para Cerrar',
    'ssi': 'Silencio',
    'sdo': 'Caída en Paso Lateral (en el 1)',
    'sdn': 'Abanico con Caída',
    'sdt': 'Caída en Paso Cruzado (en el 3)',
    'sfd': 'Caída con Lazo por la Cara (Face Loop)',
    'sda': 'Caída al Terminar la Música',
    'sdv': 'Caída en Viborita',
    'ssd': 'Caída Sentada Contrabalanceada',
    'sta': 'Caída Lanzada Cruzada (Toss Across)',
    'sdf': 'Caída en Promenade (en el 4)',
    'sid': 'Caída con Giro Interno',
    'sit': 'Caída con Giro Interno y Lazo por la Cara',
    'spd': 'Pivotes Saliendo de una Caída',
    'sic': 'Caída en Corte Hamacado Intensificado',
    'sib': 'Caída en Corte Hamacado Intensificado (Contrabalanceada)',
    'srd': 'Caída con Giro Libre',
    'slu': 'Estocada en Promenade',
    'slt': 'Estocada y Corte Girado',
    'sil': 'Estocada en Cuna con Giro Interno',
    'sos': 'Tango One Step Rápido',
    'snv': 'Innovación',
    'sad': 'Tango "Avanzado" (Sin Coincidir con la Pareja)',
    'scp': 'Inversión de Roles',
    'sbg': 'Iniciativa del Seguidor - Ochos en Viborita',
    'ssf': 'Secuencia de Práctica de Tango (Flio Tango)',
    'ssn': 'El Tango One Step',
    'ssk': 'El Tango del Patinador',
    'sst': 'El Tango 2014',
    'ssr': 'Tango Frotado',
    # --- Tango Temprano de Buenos Aires ---
    'lfs': 'Demo de una Canción Completa',
    'lrf': 'Cruces de Pies Laterales (Derecho por Delante)',
    'lrb': 'Cruces de Pies Laterales (Derecho por Detrás)',
    'llf': 'Cruces de Pies Laterales (Izquierdo por Delante)',
    'llb': 'Cruces de Pies Laterales (Izquierdo por Detrás)',
    'lcd': 'Cruces de Pies Laterales (Cambiando de Dirección)',
    'lca': 'Cruces de Pies Avanzando',
    'lml': 'Molinete (Líder como Eje)',
    'lmg': 'Molinete (Viborita del Seguidor)',
    'lmf': 'Molinete (Seguidor como Eje)',
    'lmc': 'Molinete (Girando Uno Alrededor del Otro)',
    'lms': 'Molinete (Cambiando de Dirección)',
    'llc': 'Paso Lateral (Cambiando de Dirección)',
    'lho': 'Sentada #1 (Camina 1, Pausa 1)',
    'lhw': 'Sentada #2 (Camina 2, Pausa 2)',
    'lhh': 'Sentada #3 (Camina 3, Pausa 1)',
    'lua': 'La Sentada Única (Adaptada)',
    'lsu': 'La Sentada Única',
    'lvv': 'Media Luna #2 - Vai-Ven (alias Santiagueña)',
    'lve': 'Media Luna #2 - Vai-Ven (Versión Extendida)',
    'ldc': 'Media Luna #4 - Doble Cuatro o Riojana',
    'lte': 'Media Luna #9 - Tucumana (Versión Extendida)',
    'lpf': 'Media Luna #10 - Porteña (Versión Aplanada)',
    'lna': 'Media Luna #11 - Puntana (Adaptada)',
    # --- Tango Temprano en el Mundo ---
    'efs': 'Demo de una Canción Completa',
    'ers': 'Paso Corrido',
    'eca': 'Corte A (Adelante, Lateral, Cierre, Atrás)',
    'etf': 'Corte A (con Punta al Piso)',
    'etr': 'Corte A (con Punta Elevada)',
    'eaa': 'Corte A (Ritmo 1, y, 2, 3)',
    'eaw': 'Corte A2 (Adelante, Lateral, Reemplazo, Atrás)',
    'eah': 'Corte A3 (Adelante, Adelante, Cierre, Atrás)',
    'eaf': 'Corte A4 (Adelante, Adelante, Golpe de Taco, Atrás)',
    'eav': 'Corte A5 (Adelante, Adelante, Reemplazo, Atrás)',
    'eax': 'Corte A6 (Cruce, Adelante, Cierre, Atrás)',
    'eas': 'Corte A7 (Cruce, Lanzamiento, Atrás)',
    'eat': 'Corte A7 (Lanzamiento) (Adaptado)',
    'eae': 'Corte A8 (Adelante, Barrida Adelante, Atrás)',
    'ean': 'Corte A9 (Adelante, Cierre sin Peso, Atrás)',
    'ead': 'Corte A10 (Adelante, Punta Lateral, Atrás)',
    'eal': 'Corte A11 (Atrás, Lateral, Cierre, Adelante)',
    'eac': 'Corte A12 (Atrás, Cepillado, Adelante)',
    'ear': 'Corte A13 (Desplazamiento del Pie)',
    'ecb': 'Corte B (Atrás, Lateral, Cierre, Atrás)',
    'ebw': 'Corte B2 (Atrás, Lateral, Reemplazo, Atrás)',
    'ebh': 'Corte B3 (Atrás, Lateral, Golpe de Taco, Atrás)',
    'ebf': 'Corte B4 (Atrás, Cierre sin Peso, Atrás)',
    'ebv': 'Corte B5 (Cruce por Detrás, Punta Lateral, Atrás)',
    'ecc': 'Corte C (Adelante, Adelante, Cierre, Adelante)',
    'ecd': 'Corte D (Corte de Vacilación Simple)',
    'ece': 'Corte E (Combinación con Sentada)',
    'ecf': 'Corte F (Corte de Caja Doble)',
    'eoo': 'Ochos (Estilo Abierto)',
    'eop': 'Ochos (Estilo de Puntas)',
    'eok': 'Ochos (Estilo de Patadas)',
    'eos': 'Ochos (Estilo de Barridas)',
    'eof': 'Ochos (Estilo Punto Pluma)',
    'eoe': 'El Punto Pluma (Feather Stitch)',
    'eow': 'Ochos (Estilo de Pivoteos)',
    'eob': 'Ochos Grandes y Chicos (Estilo de Pivotes)',
    'eoc': 'Ochos (Ochos Atrás)',
    'efo': 'Ochos (Solo del Seguidor)',
    'eoh': 'Las Gavillas (Sheaves)',
    'epp': 'Paseo con Puntas',
    'ems': 'Ochos (La Tijera Mayor)',
    'enm': 'El Nip Up y la Tijera Mayor',
    'eoa': 'Ochos (Versión Atrás y Adelante)',
    'esc': 'Tijeras',
    'esb': 'Tijeras Grandes y Chicas',
    'esr': 'Tijeras Grandes y Chicas con Corte Cruzado',
    'ess': 'Tijeras con Paso Lateral',
    'esi': 'Tijeras con Paso Lateral, Grandes y Chicas',
    'esa': 'Tijeras con Paso Lateral Atrás para el Líder',
    'eps': 'Promenade y Pivoteo',
    'ets': 'Promenade de Tres Pasos (Versión con Punta)',
    'etc': 'Promenade de Tres Pasos (Versión con Cierre)',
    'eta': 'Promenade de Tres Pasos (Versión con Punta y Cierre)',
    'etw': 'Promenade de Tres Pasos (Versión con Torsión)',
    'etm': 'Promenade de Tres Pasos (Versión con Zapateo)',
    'erc': 'Rueda (Chassé del Seguidor)',
    'err': 'Rueda (Chassé Cruzado del Seguidor)',
    'erg': 'Rueda (Ida y Vuelta)',
    'erf': 'Rueda (Pivote del Seguidor)',
    'ema': 'Media Luna A (Caja)',
    'eml': 'Media Luna A (Caja, Versión SQQ)',
    'eme': 'Media Luna A (Caja, Versión Extendida)',
    'emt': 'Media Luna B (Zapateos)',
    'emc': 'Media Luna C (Cruce y Traba)',
    'emd': 'Media Luna D (Barridas)',
    'emb': 'Media Luna E (Balancé)',
    'emf': 'Media Luna F (Adelante, Cierre, Atrás)',
    'emp': 'Media Luna G (Polca)',
    'emm': 'Media Luna H (La Luna Mayor)',
    'epm': 'Luna Mayor en Promenade',
    'emi': 'Media Luna I (Diamante Cruzado)',
    'esw': 'Vals Lento',
    'ewc': 'Corte de Vals',
    'ett': 'Two Step Girado',
    'ele': "L'Eventail (El Abanico)",
    'ees': 'El Paso Ocho (Eight Step)',
    'eeb': 'El Paso Ocho (Versión Retrocediendo)',
    'epb': 'Pivote: de Retroceder el Seguidor a Retroceder el Líder',
    'epd': 'Pivote Doble',
    'egp': 'Pivotes en Viborita',
    'egr': 'Viborita (Derecho por Delante)',
    'egb': 'Viborita (Derecho por Detrás)',
    'edg': 'Figura del Ebrio (Viborita del Ebrio)',
    'edr': 'El Arrastre (The Draw)',
    'ech': 'Chassé de Tango',
    'ecr': 'Chassé de Tango (Empezando con Cruce)',
    'eck': 'Chassé de Tango (Versión Retrocediendo)',
    'enu': 'El Nip Up',
    'eft': 'La Figura del Golpeteo',
    'efc': 'La Figura del Golpeteo (en Posición Cerrada)',
    'efn': 'La Figura del Golpeteo (en Posición Cerrada, Versión Lenta)',
    'efm': 'Figura de Mazurca',
    'efk': 'Paso Oblico (Rodilla Adentro, Rodilla Afuera)',
    'efh': 'Paso Oblico (Punta y Chassé)',
    'efw': 'Paso Oblico (Punta y Two Step)',
    'efv': 'El Paso de Siete (Seven Step)',
    'efr': 'La Figura del Tornillo',
    'efg': 'Caminata y Balanceo',
    'efe': 'Golpe de Taco Preliminar',
    'efy': 'Frotado Preliminar',
    'eks': 'Vacilación Simple',
    'ekr': 'Giro Hamacado (a la Derecha)',
    'ekl': 'Giro Hamacado (a la Izquierda)',
    'ekd': 'Vacilación Doble',
    'elb': 'El Paso Flexionado (Bend Step)',
    'elp': 'Promenade y Estocada',
    'edp': 'Caída',
    'ebr': 'Cambio de Pie con Flexión y Hamacada',
    'ehp': 'Cambio de Pie Manteniéndose en el Lugar',
    'eeq': 'Cambio de Pie con un Paso Rápido Extra',
    'ehb': 'Cambio de Pie con Media Caja',
    'etb': 'Caja Viajera (con Pies Juntos)',
    'ein': 'Innovación',
    'esk': 'Posición de Patinadores',
    # --- Tango de Posguerra ---
    'mwa': 'La Caminata de Tango o Promenade',
    'mco': 'El Cortez',
    'mca': 'El Chassé',
    'mel': 'El "El Sharon"',
    'msc': 'El Cortez Simple',
    'mpr': 'La Promenade de Tango',
    'mch': 'El Chasé',
    'mct': 'El Corté',
    'mms': 'El Paso de Tango de Arthur Murray',
}

data = json.load(open('data.json'))
missing = []
for s in data['sections']:
    s['name'] = SECTIONS.get(s['name'], s['name'])
    for sub in s['subs']:
        if sub['name'] and sub['name'] not in SUBS:
            missing.append(('SUB', sub['name']))
        sub['name'] = SUBS.get(sub['name'], sub['name'])
        for it in sub['items']:
            es = T.get(it['c'])
            if es and es != it['t']:
                it['e'] = it['t']   # original English kept for search
                it['t'] = es

json.dump(data, open('data_es.json', 'w'), ensure_ascii=False)
translated = sum(1 for s in data['sections'] for sub in s['subs'] for it in sub['items'] if 'e' in it)
kept = sum(1 for s in data['sections'] for sub in s['subs'] for it in sub['items'] if 'e' not in it)
print('traducidos:', translated, '| ya en español (sin cambio):', kept)
print('subsecciones sin traducción:', missing or 'ninguna')
